services:
  db:
    image: mongo:7
    container_name: gsb-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: gsb
      MONGO_INITDB_ROOT_PASSWORD: gsbpass
      MONGO_INITDB_DATABASE: gsbapplifrais
    volumes:
      - gsbdata:/data/db

  mongo-express:
    image: mongo-express
    container_name: gsb-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://gsb:gsbpass@db:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - db

volumes:
  gsbdata: